name: Build & Test Lean

on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln

      - name: Run Tests
        run: dotnet test ./Tests/bin/Release/QuantConnect.Tests.dll --filter TestCategory!=TravisExclude -- TestRunParameters.Parameter\(name=\"log-handler\", value=\"ConsoleErrorLogHandler\"\)

      - name: Generate & Publish python stubs
        run: |
          chmod +x ci_build_stubs.sh
          ./ci_build_stubs.sh -d -t -g #Ignore Publish as of since credentials are missing on CI
